/* Generated by scripts/generate-guide-completion-contract.mjs. Do not edit. */
export const GUIDE_COMPLETION_CONTRACT_VERSION = '1' as const;
export const GUIDE_COMPLETION_ARTIFACT_SHA256 = '6334c1d2c1cc9d884e317e361acce701e8f93b4d646db6c9c3abe8d4a7be795f' as const;
export const GUIDE_COMPLETION_ERROR_CODES = [
  'contract_mismatch',
  'auth_required',
  'plan_tier_required',
  'model_unavailable',
  'idempotency_conflict',
  'quota_exhausted',
  'rate_limited',
  'upstream_unavailable',
] as const;
export const GUIDE_COMPLETION_EVENT_TYPES = [
  'response_started',
  'text_delta',
  'tool_use',
  'usage',
  'completed',
  'error',
] as const;
