# TICKET_794 Phase 1 -- generates composer_templates_embed.hpp.
#
# Invoked from CMakeLists.txt via add_custom_command(... COMMAND ${CMAKE_COMMAND}
#   -D OUT=... -D LIVE_TPL=... -D LIVE_COMPOSED_TPL=... -D INDICATORS_DIR=...
#   -D NLOHMANN_JSON_INC=... -D STRATFORGE_INC_DIRS=...
#   -P generate_composer_embed.cmake).
#
# Inputs:
#   OUT                 -- absolute output header path
#   LIVE_TPL            -- packages/builder-templates/templates/live.cpp.template
#   LIVE_COMPOSED_TPL   -- packages/builder-templates/templates/live_composed.cpp.template
#   INDICATORS_DIR      -- absolute path to stratforge indicators headers
#   NLOHMANN_JSON_INC   -- absolute path to nlohmann json include root
#   STRATFORGE_INC_DIRS -- semicolon-separated stratforge include roots

if(NOT OUT OR NOT LIVE_TPL OR NOT LIVE_COMPOSED_TPL OR NOT INDICATORS_DIR)
    message(FATAL_ERROR "generate_composer_embed.cmake: missing required variable")
endif()

# --- Read live_composed template verbatim. ---
file(READ "${LIVE_COMPOSED_TPL}" _composed_body)

# --- Read live.cpp.template and extract the qnx_live namespace body. ---
file(READ "${LIVE_TPL}" _live_body)
string(REGEX MATCH "namespace qnx_live[ \t]*\\{[\r\n]+(.*[\r\n])\\}[ \t]*// namespace qnx_live" _m "${_live_body}")
if(NOT CMAKE_MATCH_1)
    message(FATAL_ERROR "could not extract qnx_live namespace body from ${LIVE_TPL}")
endif()
set(_qnx_runtime "${CMAKE_MATCH_1}")

# --- Enumerate indicator headers. ---
file(GLOB _indicator_hdrs RELATIVE "${INDICATORS_DIR}" "${INDICATORS_DIR}/*.hpp")
set(_indicator_entries "")
foreach(_h IN LISTS _indicator_hdrs)
    string(REGEX REPLACE "\\.hpp$" "" _base "${_h}")
    string(TOLOWER "${_base}" _base_lc)
    set(_indicator_entries "${_indicator_entries}    \"${_base_lc}\",\n")
endforeach()

# --- Helper: escape a string for embedding as a raw C++ literal via R"(...)". ---
# We use a delimiter that is extremely unlikely to appear inside templates.
set(_delim "QNX_TPL_DELIM")
function(_assert_no_delim val name)
    string(FIND "${val}" "${_delim}" _pos)
    if(NOT _pos EQUAL -1)
        message(FATAL_ERROR "raw-string delimiter clash in ${name}; pick a new delimiter")
    endif()
endfunction()
_assert_no_delim("${_composed_body}" "live_composed.cpp.template")
_assert_no_delim("${_qnx_runtime}" "live.cpp.template")

# --- Stratforge / nlohmann include dirs. ---
set(_inc_entries "")
foreach(_d IN LISTS STRATFORGE_INC_DIRS)
    if(_d)
        set(_inc_entries "${_inc_entries}    \"${_d}\",\n")
    endif()
endforeach()
set(_inc_entries "${_inc_entries}    nullptr,\n")

# Make sure NLOHMANN_JSON_INC is at least an empty string if unset.
if(NOT NLOHMANN_JSON_INC)
    set(NLOHMANN_JSON_INC "")
endif()

# --- Compose header. ---
set(_header "// AUTO-GENERATED by generate_composer_embed.cmake.\n")
set(_header "${_header}// Do not edit; regenerated when live.cpp.template, live_composed.cpp.template,\n")
set(_header "${_header}// or the stratforge indicators directory changes.\n\n")
set(_header "${_header}#pragma once\n\n")
set(_header "${_header}namespace stratforge::live::composer {\n\n")
set(_header "${_header}inline constexpr const char* kLiveComposedTemplate = R\"${_delim}(${_composed_body})${_delim}\";\n\n")
set(_header "${_header}inline constexpr const char* kQnxLiveRuntime = R\"${_delim}(${_qnx_runtime})${_delim}\";\n\n")
set(_header "${_header}inline constexpr const char* kStratforgeIndicatorAcceptList[] = {\n${_indicator_entries}    nullptr,\n};\n\n")
set(_header "${_header}inline constexpr const char* kNlohmannJsonIncludeDir = \"${NLOHMANN_JSON_INC}\";\n\n")
set(_header "${_header}inline constexpr const char* kStratforgeIncludeDirs[] = {\n${_inc_entries}};\n\n")
set(_header "${_header}}  // namespace stratforge::live::composer\n")

file(WRITE "${OUT}" "${_header}")
