/**
 * NexusHubPage - The primary landing page for StratCraft
 *
 * Uses VIEW_REGISTRY for centralized plugin-to-view mapping.
 *
 * Flat module list replacing the previous 2-column category split.
 *
 * @see TICKET_069 - Centralized View Registry
 */

import React, { useMemo, useCallback, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { WEBSITE_PRICING_URL } from '@StratCraft/types';
import { CSS_VAR_FALLBACKS } from '@shared/constants/colors';
import { Cpu, Power, Lock, Search, Factory, Activity, Link as LinkIcon } from 'lucide-react';
import { usePluginManager } from '@/lib/plugin-manager';
import { useAppStore } from '@/stores';
import { cn } from '@/lib/utils';
import { StatusDot, MetalNameplate } from '@/components/common';
import { getViewIdByPluginId, getPluginIconPath, type ViewId } from '@/config';
import { useIsPublicRelease } from '@/hooks/useDistribution';
import { resolveManifestI18n } from '@/lib/manifest-i18n';
import type { PluginInstance } from '@shared/types';

// TICKET_632_1: Pro feature card type (loaded from generated JSON)
interface ProFeatureCard {
  id: string;
  name: string;
  description: string;
  icon: string;
  badge: string;
  category: string;
  sourcePlugin: string;
}

// TICKET_632_1: Icon mapping for Pro feature cards (lucide-react)
const PRO_CARD_ICONS: Record<string, React.FC<{ className?: string }>> = {
  Search,
  Factory,
  Activity,
  Link: LinkIcon,
};

// TICKET_632_1: Pro feature cards generated by publish-community.sh.
// In full distribution this file is an empty array []. In public release it contains card data.
import _proFeatureCards from '@shared/generated/pro-feature-cards.json';
const proFeatureCards = _proFeatureCards as ProFeatureCard[];

export const NexusHubPage: React.FC = () => {
  const { t } = useTranslation('ui');
  const { plugins, loading, pendingLazyIds, activatePlugin, deactivatePlugin } = usePluginManager();
  const { setActiveView } = useAppStore();
  const isPublic = useIsPublicRelease();
  const [upgradeCard, setUpgradeCard] = useState<ProFeatureCard | null>(null);

  // Handle plugin click - navigate to plugin view
  // TICKET_1231: enabled plugins pending lazy activation are navigable too;
  // navigation itself triggers their onView activation.
  const handlePluginClick = useCallback((plugin: PluginInstance) => {
    const pluginId = plugin.manifest.id;
    if (!plugin.state.active && !pendingLazyIds.includes(pluginId)) return;

    const viewId = getViewIdByPluginId(pluginId);

    if (!viewId) {
      console.warn(`[W:NEXUS:VIEW_MAPPING_NOT_FOUND] No view mapping for plugin: ${pluginId}`);
      return;
    }

    // Navigate to plugin view
    console.info(`[NexusHubPage] Navigating to view: ${viewId}`);
    setActiveView(viewId as ViewId);
  }, [setActiveView, pendingLazyIds]);

  // Handle plugin toggle - activate or deactivate
  // TICKET_269: Bottom section click = toggle only (no navigation)
  // Navigation happens only when clicking top LinkedPluginsGrid cards
  const handleTogglePlugin = useCallback(async (e: React.MouseEvent, pluginId: string, currentState: boolean) => {
    e.stopPropagation();
    if (currentState) {
      console.info(`[NexusHubPage] Deactivating plugin: ${pluginId}`);
      await deactivatePlugin(pluginId);
    } else {
      console.info(`[NexusHubPage] Activating plugin: ${pluginId}`);
      await activatePlugin(pluginId);
    }
  }, [activatePlugin, deactivatePlugin]);

  // All user-facing plugins (Tier 0 foundation plugins are internal)
  const categorizedPlugins = useMemo(() => {
    const userFacingPlugins = plugins.filter(p => (p.manifest.tier ?? 1) !== 0);
    return {
      active: plugins.filter(p => p.state.active),
      all: userFacingPlugins,
    };
  }, [plugins]);

  if (loading) {
    return (
      <div className="flex h-full items-center justify-center bg-StratCraftsAI terminal-theme">
        <div className="flex flex-col items-center gap-4">
          <div className="relative">
            <div className="relative w-16 h-16 border-2 border-color-terminal-accent-teal/30 border-t-color-terminal-accent-teal rounded-full animate-spin" />
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="w-2 h-2 bg-color-terminal-accent-teal rounded-full animate-pulse" />
            </div>
          </div>
          <p className="text-small terminal-mono text-color-terminal-accent-teal animate-pulse uppercase tracking-widest">
            {t('nexusHub.initializingSystems')}
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="p-6 h-full flex flex-col gap-6 overflow-auto terminal-theme bg-StratCraftsAI relative">
      {/* Primary Enabled Modules (Top Control Center - Simplified) */}
      <div className="z-10 relative">
        {/* Metallic Nameplate Header */}
        <div className="mb-8">
          <MetalNameplate title="STRATCRAFT" subtitle={t('nexusHub.connectTheAlpha')} className="shadow-xl max-w-xl" />
        </div>

        {/* TICKET_269: LinkedPluginsGrid - 2x2 grid for all linked plugins */}
        {/* TICKET_1231: linked = active OR enabled-pending-lazy-activation */}
        <div className="mb-6">
          <LinkedPluginsGrid
            plugins={plugins}
            pendingLazyIds={pendingLazyIds}
            accentColor="blue"
            onToggle={handleTogglePlugin}
            onNavigate={handlePluginClick}
            t={t}
          />
        </div>

      </div>

      {/* Flat Module List - All user-facing plugins */}
      <div className="flex-1 min-h-0 relative z-10">
        <div className="flex flex-col h-full rounded-xl overflow-hidden border border-white/10 border-t-4 border-t-blue-500">
          {/* Section Header */}
          <div className="p-5 border-b border-white/5">
            <h2 className="text-lg font-bold uppercase tracking-tight text-blue-500">
              {t('nexusHub.modules')}
            </h2>
            <p className="text-[12px] text-color-terminal-text-secondary leading-relaxed pl-1 mt-2">
              {t('nexusHub.modulesDescription')}
            </p>
          </div>

          {/* Plugin List */}
          <div className="flex-1 overflow-auto p-4 grid grid-cols-2 gap-2 auto-rows-min content-start">
            {categorizedPlugins.all.length === 0 && (!isPublic || proFeatureCards.length === 0) ? (
              <div className="col-span-2 flex flex-col items-center justify-center h-48 text-color-terminal-text-muted/40 border-2 border-white/10 rounded-xl bg-transparent">
                <Cpu className="w-8 h-8 mb-2 opacity-20" />
                <span className="text-micro uppercase font-bold tracking-widest opacity-50">{t('nexusHub.noModulesAvailable')}</span>
              </div>
            ) : (
              <>
                {categorizedPlugins.all.map((plugin) => (
                  <CompactPluginCard
                    key={plugin.manifest.id}
                    plugin={plugin}
                    pendingLazy={pendingLazyIds.includes(plugin.manifest.id)}
                    accentColor="blue"
                    onToggle={handleTogglePlugin}
                    onNavigate={handlePluginClick}
                    t={t}
                  />
                ))}
                {/* TICKET_632_1: Pro feature cards (public release only) */}
                {isPublic && proFeatureCards.map((card) => (
                  <ProFeatureCardItem
                    key={card.id}
                    card={card}
                    onClick={() => setUpgradeCard(card)}
                  />
                ))}
              </>
            )}
          </div>

          {/* Footer */}
          <div className="p-3 px-5 border-t border-white/10 bg-transparent flex justify-between items-center backdrop-blur-md">
            <span className="text-tiny text-color-terminal-text-secondary font-medium uppercase tracking-wider">
              {/* TICKET_1231: linked count includes enabled plugins pending lazy activation */}
              {t('nexusHub.linking')}: <span className="text-white font-mono">{categorizedPlugins.all.filter(p => p.state.active || pendingLazyIds.includes(p.manifest.id)).length}</span> / {categorizedPlugins.all.length}
            </span>
            <button
              className="text-tiny font-bold transition-colors uppercase flex items-center gap-1 text-blue-500 hover:brightness-125"
              onClick={() => setActiveView('marketplace')}
            >
              {t('nexusHub.registry')} <span className="text-xs">&rarr;</span>
            </button>
          </div>
        </div>
      </div>

      {/* TICKET_632_1: Pro upgrade prompt dialog */}
      {upgradeCard && (
        <ProUpgradeDialog card={upgradeCard} onClose={() => setUpgradeCard(null)} />
      )}
    </div>
  );
};

/**
 * TICKET_632_1: Pro feature card displayed in public release NexusHub module list.
 * Shows Pro badge, locked state, and opens upgrade dialog on click.
 */
interface ProFeatureCardItemProps {
  card: ProFeatureCard;
  onClick: () => void;
}

const ProFeatureCardItem: React.FC<ProFeatureCardItemProps> = ({ card, onClick }) => {
  const IconComponent = PRO_CARD_ICONS[card.icon] || Cpu;

  return (
    <div
      className="group/item relative p-2 rounded-lg border border-white/10 transition-all overflow-hidden h-[72px] flex items-center cursor-pointer bg-transparent hover:border-amber-500/30 hover:bg-amber-500/5"
      onClick={onClick}
    >
      <div className="flex items-center gap-2 flex-1 min-w-0">
        <div className="w-7 h-7 flex items-center justify-center rounded bg-transparent border border-white/10">
          <IconComponent className="w-4 h-4 text-amber-500/50" />
        </div>
        <div className="flex flex-col min-w-0 flex-1">
          <span className="text-[12px] font-bold tracking-tight truncate text-white/40">
            {card.name}
          </span>
          <span className="text-[10px] text-white/20 truncate">{card.description}</span>
        </div>
      </div>
      <div className="flex items-center gap-1.5 shrink-0">
        <span className="text-[9px] font-bold uppercase tracking-wider text-amber-500 bg-amber-500/10 px-1.5 py-0.5 rounded">
          {card.badge}
        </span>
        <Lock className="w-3 h-3 text-white/20" />
      </div>
    </div>
  );
};

/**
 * TICKET_632_1: Pro upgrade prompt dialog.
 * Shown when a user clicks a Pro feature card in public release.
 */
interface ProUpgradeDialogProps {
  card: ProFeatureCard;
  onClose: () => void;
}

const ProUpgradeDialog: React.FC<ProUpgradeDialogProps> = ({ card, onClose }) => {
  const { t } = useTranslation('ui');
  const IconComponent = PRO_CARD_ICONS[card.icon] || Cpu;
  const mouseDownOnBackdrop = useRef(false);

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm"
      onMouseDown={() => { mouseDownOnBackdrop.current = true; }}
      onMouseUp={() => {
        if (mouseDownOnBackdrop.current) onClose();
        mouseDownOnBackdrop.current = false;
      }}
    >
      <div
        className="border border-white/10 rounded-xl p-8 max-w-md w-full mx-4 shadow-2xl"
        style={{ backgroundColor: CSS_VAR_FALLBACKS.BG_DEEP_DARK }}
        onMouseDown={(e) => e.stopPropagation()}
      >
        <div className="flex flex-col items-center text-center">
          <div className="mb-4 p-4 rounded-full bg-amber-500/10 border border-amber-500/20">
            <IconComponent className="w-8 h-8 text-amber-500" />
          </div>
          <h3 className="text-xl font-bold text-white mb-2">{card.name}</h3>
          <span className="text-[10px] font-bold uppercase tracking-wider text-amber-500 bg-amber-500/10 px-2 py-1 rounded mb-4">
            {card.badge}
          </span>
          <p className="text-white/50 mb-8">{card.description}</p>
          <div className="flex gap-3 w-full">
            <button
              onClick={() => {
                window.electronAPI?.marketplace?.openPurchaseUrl(WEBSITE_PRICING_URL);
                onClose();
              }}
              className="flex-1 px-4 py-2.5 bg-amber-500 text-black font-medium rounded hover:bg-amber-400 transition-colors"
            >
              {t('auth.viewPlans', 'View Plans')}
            </button>
            <button
              onClick={onClose}
              className="px-4 py-2.5 border border-white/20 text-white/60 rounded hover:bg-white/5 transition-colors"
            >
              {t('common.close', 'Close')}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

/**
 * TICKET_269: LinkedPluginsGrid - Shows all linked plugins in 2x2 grid
 * Replaces ActiveModuleSlot to support multiple linked plugins
 * TICKET_1231: linked = active OR enabled-pending-lazy-activation (plugins
 * declaring onView activation events stay pending until first navigation).
 */
interface LinkedPluginsGridProps {
  plugins: PluginInstance[];
  pendingLazyIds: string[];
  accentColor: 'gold' | 'teal' | 'blue';
  onToggle: (e: React.MouseEvent, pluginId: string, currentState: boolean) => void;
  onNavigate: (plugin: PluginInstance) => void;
  t: (key: string, options?: Record<string, string>) => string;
}

const LinkedPluginsGrid: React.FC<LinkedPluginsGridProps> = ({ plugins, pendingLazyIds, accentColor, onToggle, onNavigate, t }) => {
  // TICKET_294: Order by activatedAt to preserve user click order
  // TICKET_1231: pending-lazy plugins have no activatedAt yet -- sort last
  const linkedPlugins = plugins
    .filter(p => p.state.active || pendingLazyIds.includes(p.manifest.id))
    .sort((a, b) => (a.state.activatedAt ?? Number.MAX_SAFE_INTEGER) - (b.state.activatedAt ?? Number.MAX_SAFE_INTEGER));
  const minSlots = 4;
  // Dynamic rows: show all linked plugins, minimum 4 slots (2x2)
  const emptySlots = Math.max(0, minSlots - linkedPlugins.length);

  return (
    <div className="grid grid-cols-2 gap-2">
      {linkedPlugins.map((plugin) => (
        <CompactPluginCard
          key={plugin.manifest.id}
          plugin={plugin}
          pendingLazy={pendingLazyIds.includes(plugin.manifest.id)}
          accentColor={accentColor}
          onToggle={onToggle}
          onNavigate={onNavigate}
          isLinked={true}
          t={t}
        />
      ))}
      {Array(emptySlots).fill(null).map((_, i) => (
        <div
          key={`empty-${i}`}
          className="h-[72px] rounded-lg border border-white/10 border-dashed bg-transparent flex items-center justify-center"
        >
          <span className="text-[8px] terminal-mono uppercase tracking-[0.15em] text-white/20">
            {t('nexusHub.emptySlot')}
          </span>
        </div>
      ))}
    </div>
  );
};

/**
 * TICKET_269: CompactPluginCard - Unified compact card (72px height)
 * Used in both LinkedPluginsGrid (top) and flat module list (bottom)
 */
interface CompactPluginCardProps {
  plugin: PluginInstance;
  /** TICKET_1231: enabled, waiting for navigation-triggered activation */
  pendingLazy?: boolean;
  accentColor: 'teal' | 'gold' | 'blue';
  onToggle: (e: React.MouseEvent, pluginId: string, currentState: boolean) => void;
  onNavigate: (plugin: PluginInstance) => void;
  isLinked?: boolean;
  t: (key: string, options?: Record<string, string>) => string;
}

const CompactPluginCard: React.FC<CompactPluginCardProps> = ({ plugin, pendingLazy, accentColor, onToggle, onNavigate, isLinked, t }) => {
  const textColorMap = {
    teal: 'text-color-terminal-accent-teal',
    gold: 'text-color-terminal-accent-gold',
    blue: 'text-blue-500',
  };

  const active = plugin.state.active;
  // TICKET_1231: "linked" = user-enabled; pending-lazy counts as linked so the
  // bottom-list toggle disables it (instead of force-activating it eagerly).
  const linked = active || !!pendingLazy;
  // TICKET_295: Visual brightness decoupled from activation state
  // Top area (isLinked): always bright; Bottom: bright if not linked, dim if already linked above
  const appearsBright = isLinked || !linked;
  const textColors = textColorMap[accentColor];
  const iconPath = getPluginIconPath(plugin.manifest.id);
  // TICKET_786_6 Phase 1: pull translated manifest for the card label.
  const localizedManifest = resolveManifestI18n(plugin.manifest);

  return (
    <div
      className={cn(
        "group/item relative p-2 rounded-lg border border-white/10 transition-all overflow-hidden h-[72px] flex items-center cursor-pointer bg-transparent",
        linked && !isLinked && "opacity-60 grayscale hover:grayscale-0 hover:opacity-100"
      )}
      onClick={(e) => isLinked ? onNavigate(plugin) : onToggle(e, plugin.manifest.id, linked)}
    >
      <div className="flex items-center gap-2 flex-1 min-w-0">
        {iconPath ? (
          <div className="w-7 h-7 flex items-center justify-center overflow-hidden shrink-0 bg-transparent rounded border border-white/10 p-0.5">
            <img
              src={iconPath}
              alt="icon"
              className={cn(
                "w-full h-full object-contain brightness-0 invert transition-opacity",
                appearsBright ? "opacity-100" : "opacity-30"
              )}
            />
          </div>
        ) : (
          <div className="w-7 h-7 flex items-center justify-center rounded bg-transparent border border-white/10">
            <Cpu className={cn("w-4 h-4", appearsBright ? textColors : "opacity-30")} />
          </div>
        )}
        <div className="flex flex-col min-w-0 flex-1">
          <span className={cn(
            "text-[12px] font-bold transition-colors tracking-tight truncate",
            appearsBright ? "text-white" : "text-color-terminal-text-muted"
          )}>
            {localizedManifest.displayName || localizedManifest.name}
          </span>
          <span className="text-[12px] opacity-40">v{plugin.manifest.version}</span>
        </div>
      </div>
      <div className="flex items-center gap-1.5 shrink-0">
        {isLinked && (
          <button
            onClick={(e) => { e.stopPropagation(); onToggle(e, plugin.manifest.id, true); }}
            className="p-1 rounded hover:bg-red-500/20 text-white/20 hover:text-red-500 transition-all"
            title={t('nexusHub.deactivate')}
          >
            <Power className="w-3 h-3" />
          </button>
        )}
        {/* TICKET_1231: idle = enabled, activates on first navigation */}
        <StatusDot status={active ? 'online' : pendingLazy ? 'idle' : 'offline'} size="sm" />
      </div>
    </div>
  );
};

export default NexusHubPage;
