// TICKET_794 Phase 1 -- composed source emission.

#include "source_emitter.hpp"

#include "composer_templates_embed.hpp"  // generated by CMake: kLiveComposedTemplate, kQnxLiveRuntime, kStratforgeIndicatorAcceptList

#include <algorithm>
#include <array>
#include <cctype>
#include <cstdint>
#include <limits>
#include <regex>
#include <sstream>
#include <string>
#include <unordered_set>

namespace stratforge::live::composer {

namespace {

// Replace every occurrence of needle in haystack with replacement.
std::string replaceAll(std::string haystack, std::string_view needle, std::string_view replacement) {
    std::string out;
    out.reserve(haystack.size());
    std::size_t pos = 0;
    while (true) {
        const std::size_t next = haystack.find(needle, pos);
        if (next == std::string::npos) {
            out.append(haystack, pos, std::string::npos);
            return out;
        }
        out.append(haystack, pos, next - pos);
        out.append(replacement.data(), replacement.size());
        pos = next + needle.size();
    }
}

// Escape an arbitrary UTF-8 string for inclusion in a C++ "..." literal.
std::string cppLiteral(std::string_view raw) {
    std::string out;
    out.reserve(raw.size() + 2);
    out.push_back('"');
    for (char ch : raw) {
        switch (ch) {
            case '\\': out.append("\\\\"); break;
            case '"':  out.append("\\\""); break;
            case '\n': out.append("\\n"); break;
            case '\r': out.append("\\r"); break;
            case '\t': out.append("\\t"); break;
            default:
                if (static_cast<unsigned char>(ch) < 0x20) {
                    char buf[8];
                    std::snprintf(buf, sizeof(buf), "\\x%02x", static_cast<unsigned>(static_cast<unsigned char>(ch)));
                    out.append(buf);
                } else {
                    out.push_back(ch);
                }
                break;
        }
    }
    out.push_back('"');
    return out;
}

// Set of header basenames (lowercased, no .hpp) discovered under
// the stratforge indicators include directory at composer build time.
const std::unordered_set<std::string>& acceptedIndicatorHeaders() {
    static const std::unordered_set<std::string> set = [] {
        std::unordered_set<std::string> s;
        for (const char* const* p = kStratforgeIndicatorAcceptList; *p != nullptr; ++p) {
            s.insert(*p);
        }
        return s;
    }();
    return set;
}

void rejectUnsupportedIndicators(const ComposerInput& input) {
    // TICKET_794 sec 10.2: scan algorithmCode for stratforge::indicators::X and
    // nonabt::indicators::X (the audit script accepts either prefix) and reject
    // before invoking the compiler so the user gets a clean error.
    static const std::regex re(
        R"(\b(?:stratforge|nonabt)::indicators::([A-Za-z_][A-Za-z0-9_]*))");
    const auto& accepted = acceptedIndicatorHeaders();
    for (const auto& c : input.components) {
        auto begin = std::sregex_iterator(c.algorithmCode.begin(), c.algorithmCode.end(), re);
        auto end = std::sregex_iterator();
        for (auto it = begin; it != end; ++it) {
            std::string ind = (*it)[1].str();
            std::string lower = ind;
            std::transform(lower.begin(), lower.end(), lower.begin(),
                           [](unsigned char ch) { return static_cast<char>(std::tolower(ch)); });
            if (accepted.find(lower) == accepted.end()) {
                throw ComposerError(
                    ErrorCode::IndicatorNotAvailable,
                    "indicator '" + ind + "' is not in the stratforge accept-list",
                    "no stratforge/indicators/" + lower + ".hpp header found at composer build time");
            }
        }
    }
}

std::string buildIncludesBlock(const ComposerInput& input) {
    // TICKET_794 sec 9: STRATFORGE_INCLUDES derived from indicators referenced.
    // Provisional accept-list scan -- emit one `#include` per unique indicator
    // header referenced across all components.
    static const std::regex re(
        R"(\b(?:stratforge|nonabt)::indicators::([A-Za-z_][A-Za-z0-9_]*))");
    std::unordered_set<std::string> headers;
    for (const auto& c : input.components) {
        auto begin = std::sregex_iterator(c.algorithmCode.begin(), c.algorithmCode.end(), re);
        for (auto it = begin; it != std::sregex_iterator(); ++it) {
            std::string ind = (*it)[1].str();
            std::transform(ind.begin(), ind.end(), ind.begin(),
                           [](unsigned char ch) { return static_cast<char>(std::tolower(ch)); });
            headers.insert(ind);
        }
    }
    std::string block;
    // Stable ordering for deterministic .cpp output (sec 7 cache determinism).
    std::vector<std::string> sorted(headers.begin(), headers.end());
    std::sort(sorted.begin(), sorted.end());
    for (const auto& h : sorted) {
        block += "#include <stratforge/indicators/";
        block += h;
        block += ".hpp>\n";
    }
    return block;
}

// Derive analysis context slots. Phase 0 audit returned 0 rows so the
// convention is freshly defined here: each ctx.<name> referenced by any
// component is exposed as a `double` slot, plus a `<name>_ready` int sentinel
// (since some components flag readiness). Bar fields (ctx.bar.*) are excluded.
std::string buildContextSlots(const ComposerInput& input) {
    static const std::regex re(R"(\bctx\.([A-Za-z_][A-Za-z0-9_]*))");
    std::unordered_set<std::string> slots;
    for (const auto& c : input.components) {
        auto begin = std::sregex_iterator(c.algorithmCode.begin(), c.algorithmCode.end(), re);
        for (auto it = begin; it != std::sregex_iterator(); ++it) {
            std::string name = (*it)[1].str();
            if (name == "bar") continue;
            slots.insert(name);
        }
    }
    std::vector<std::string> sorted(slots.begin(), slots.end());
    std::sort(sorted.begin(), sorted.end());
    std::string out;
    for (const auto& name : sorted) {
        // Use double for value slots, int for *_ready sentinels.
        if (name.size() > 6 && name.ends_with("_ready")) {
            out += "    int ";
            out += name;
            out += " = 0;\n";
        } else {
            out += "    double ";
            out += name;
            out += " = 0.0;\n";
        }
    }
    return out;
}

// --- Baked parameter emission (TICKET_1125 Phase 5 / C2). ---
// Every parameter value is known at codegen time, so the generated TU carries
// scalar leaves as `inline constexpr` constants plus one builder function per
// role; the strategy performs no JSON parsing at runtime.

// Sanitize an arbitrary JSON key path element into a C++ identifier fragment.
std::string sanitizeIdentFragment(std::string_view raw) {
    std::string out;
    out.reserve(raw.size());
    for (char ch : raw) {
        const auto uc = static_cast<unsigned char>(ch);
        out.push_back(std::isalnum(uc) ? ch : '_');
    }
    return out;
}

class ParamBaker {
public:
    // Emits the builder function for one role and accumulates its constexpr
    // leaf constants. Deterministic: object keys iterate in nlohmann's sorted
    // order; identifier collisions resolve by a stable numeric suffix.
    void addRole(const std::string& role, const nlohmann::json& params) {
        builders_ += "inline nlohmann::json ";
        builders_ += role;
        builders_ += "_params() {\n    nlohmann::json j;\n";
        emitValue(role, "j", params);
        builders_ += "    return j;\n}\n\n";
    }

    // Full `namespace qnx_baked_params { ... }` block for the template slot.
    std::string block() const {
        std::string out = "namespace qnx_baked_params {\n\n";
        out += constants_;
        if (!constants_.empty()) out += '\n';
        out += builders_;
        out += "}  // namespace qnx_baked_params";
        return out;
    }

private:
    std::string uniqueName(const std::string& base) {
        std::string name = base;
        int suffix = 2;
        while (!usedNames_.insert(name).second) {
            name = base + "_" + std::to_string(suffix++);
        }
        return name;
    }

    void emitConstant(std::string_view type, const std::string& name,
                      const std::string& valueExpr) {
        constants_ += "inline constexpr ";
        constants_ += type;
        constants_ += ' ';
        constants_ += name;
        constants_ += " = ";
        constants_ += valueExpr;
        constants_ += ";\n";
    }

    void emitValue(const std::string& namePath, const std::string& accessor,
                   const nlohmann::json& value) {
        switch (value.type()) {
            case nlohmann::json::value_t::object:
                if (value.empty()) {
                    builders_ += "    " + accessor + " = nlohmann::json::object();\n";
                    return;
                }
                for (const auto& [key, child] : value.items()) {
                    emitValue(namePath + "_" + sanitizeIdentFragment(key),
                              accessor + "[" + cppLiteral(key) + "]", child);
                }
                return;
            case nlohmann::json::value_t::array:
                if (value.empty()) {
                    builders_ += "    " + accessor + " = nlohmann::json::array();\n";
                    return;
                }
                for (std::size_t i = 0; i < value.size(); ++i) {
                    emitValue(namePath + "_" + std::to_string(i),
                              accessor + "[" + std::to_string(i) + "]", value[i]);
                }
                return;
            case nlohmann::json::value_t::null:
                builders_ += "    " + accessor + " = nullptr;\n";
                return;
            default:
                break;
        }
        // Scalar leaf: constexpr constant + assignment. Type mirrors the
        // nlohmann storage type so baked values compare identical to the
        // former runtime-parse path.
        const std::string name = uniqueName(namePath);
        if (value.is_boolean()) {
            emitConstant("bool", name, value.get<bool>() ? "true" : "false");
        } else if (value.is_number_unsigned()) {
            // ULL suffix: an unsuffixed decimal literal above INT64_MAX is
            // ill-formed (compilers accept it only as a warning extension).
            emitConstant("std::uint64_t", name, value.dump() + "ULL");
        } else if (value.is_number_integer()) {
            // INT64_MIN has no literal form: -9223372036854775808LL is unary
            // minus applied to a literal that overflows long long.
            emitConstant("std::int64_t", name,
                         value.get<std::int64_t>() == std::numeric_limits<std::int64_t>::min()
                             ? std::string("(-9223372036854775807LL - 1)")
                             : value.dump() + "LL");
        } else if (value.is_number_float()) {
            // dump() emits the shortest round-trip decimal form, which is a
            // valid C++ double literal.
            emitConstant("double", name, value.dump());
        } else if (value.is_string()) {
            emitConstant("std::string_view", name,
                         cppLiteral(value.get_ref<const std::string&>()));
        } else {
            throw ComposerError(ErrorCode::Internal,
                                "unsupported JSON parameter type at '" + namePath + "'");
        }
        builders_ += "    " + accessor + " = " + name + ";\n";
    }

    std::unordered_set<std::string> usedNames_;
    std::string constants_;
    std::string builders_;
};

} // namespace

std::string extractClassName(std::string_view code) {
    // TICKET_794 sec 9: `class\s+(\w+)\s*[:final]` -- accept either base list,
    // `final`, or just `{` after the class name. We use a slightly looser regex
    // and require the class to be followed by whitespace+ {/:/final.
    static const std::regex re(
        R"(class\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?:final\b|:|\{))");
    std::cmatch m;
    if (std::regex_search(code.data(), code.data() + code.size(), m, re)) {
        return m[1].str();
    }
    return {};
}

std::string canonicalComponents(const std::vector<Component>& components) {
    // TICKET_794 sec 7: canonical = components sorted by role
    // (analysis/entry/exit), each serialised as algorithmCode || 0x1f || parameters,
    // joined by 0x1e between components.
    std::array<std::string, 3> ordered;
    for (const auto& c : components) {
        const std::size_t idx = (c.role == "analysis") ? 0 : (c.role == "entry") ? 1 : 2;
        ordered[idx] = c.algorithmCode + '\x1f' + c.parameters;
    }
    std::string out;
    for (std::size_t i = 0; i < ordered.size(); ++i) {
        if (i > 0) out.push_back('\x1e');
        out += ordered[i];
    }
    return out;
}

EmittedSource emitComposedSource(const ComposerInput& input) {
    rejectUnsupportedIndicators(input);

    // Sort components by sortOrder so concatenation order is deterministic.
    std::vector<Component> ordered = input.components;
    std::sort(ordered.begin(), ordered.end(),
              [](const Component& a, const Component& b) { return a.sortOrder < b.sortOrder; });

    EmittedSource out;
    const Component* analysis = nullptr;
    const Component* entry = nullptr;
    const Component* exit = nullptr;
    for (const auto& c : ordered) {
        if (c.role == "analysis") analysis = &c;
        else if (c.role == "entry") entry = &c;
        else if (c.role == "exit") exit = &c;
    }
    if (analysis == nullptr || entry == nullptr) {
        throw ComposerError(ErrorCode::ComponentMissing,
                            "analysis and entry components are both required");
    }

    out.analysisClass = extractClassName(analysis->algorithmCode);
    out.entryClass = extractClassName(entry->algorithmCode);
    if (out.analysisClass.empty()) {
        throw ComposerError(ErrorCode::InputInvalid,
                            "could not extract class name from analysis component algorithmCode");
    }
    if (out.entryClass.empty()) {
        throw ComposerError(ErrorCode::InputInvalid,
                            "could not extract class name from entry component algorithmCode");
    }
    if (exit != nullptr) {
        out.exitClass = extractClassName(exit->algorithmCode);
        if (out.exitClass.empty()) {
            throw ComposerError(ErrorCode::InputInvalid,
                                "could not extract class name from exit component algorithmCode");
        }
    }

    std::string source(kLiveComposedTemplate);

    source = replaceAll(source, "{{STRATEGY_ID}}", input.strategyId);
    source = replaceAll(source, "{{STRATFORGE_VERSION}}", input.stratforgeVersion);
    source = replaceAll(source, "{{STRATFORGE_INCLUDES}}", buildIncludesBlock(input));
    source = replaceAll(source, "{{QNX_LIVE_RUNTIME}}", kQnxLiveRuntime);
    source = replaceAll(source, "{{ANALYSIS_CONTEXT_SLOTS}}", buildContextSlots(input));

    std::string componentDefs;
    for (const auto* comp : {analysis, entry, exit}) {
        if (comp == nullptr) continue;
        componentDefs += "// component role=";
        componentDefs += comp->role;
        componentDefs += " sortOrder=";
        componentDefs += std::to_string(comp->sortOrder);
        componentDefs += '\n';
        componentDefs += comp->algorithmCode;
        componentDefs += "\n\n";
    }
    source = replaceAll(source, "{{COMPONENT_CLASS_DEFINITIONS}}", componentDefs);

    source = replaceAll(source, "{{ANALYSIS_CLASS}}", out.analysisClass);
    source = replaceAll(source, "{{ENTRY_CLASS}}", out.entryClass);

    if (exit != nullptr) {
        source = replaceAll(source, "{{EXIT_MEMBER_DECL}}",
                            "    " + out.exitClass + " exit_;\n");
        source = replaceAll(source, "{{EXIT_PARAM_BIND}}",
                            "        exit_.set_params(qnx_baked_params::exit_params());\n");
        source = replaceAll(source, "{{EXIT_EVAL_EXPR}}", "exit_.evaluate(ctx)");
        source = replaceAll(source, "{{EXIT_REASON_EXPR}}", "exit_.reason()");
    } else {
        source = replaceAll(source, "{{EXIT_MEMBER_DECL}}", "");
        source = replaceAll(source, "{{EXIT_PARAM_BIND}}", "");
        source = replaceAll(source, "{{EXIT_EVAL_EXPR}}", "false");
        source = replaceAll(source, "{{EXIT_REASON_EXPR}}", "std::string(\"exit\")");
    }

    // BAKED_PARAM_CONSTANTS (TICKET_1125 Phase 5): per-role parameters parsed
    // here at codegen time and emitted as constexpr constants + builder
    // functions -- the generated strategy performs no runtime JSON parameter
    // parsing. Unparseable parameters degrade to {} exactly as the former
    // runtime path did.
    ParamBaker baker;
    for (const auto* comp : {analysis, entry, exit}) {
        if (comp == nullptr) continue;
        nlohmann::json p = nlohmann::json::object();
        if (!comp->parameters.empty()) {
            try {
                p = nlohmann::json::parse(comp->parameters);
            } catch (const std::exception&) {
                p = nlohmann::json::object();
            }
        }
        baker.addRole(comp->role, p);
    }
    source = replaceAll(source, "{{BAKED_PARAM_CONSTANTS}}", baker.block());

    out.source = std::move(source);
    return out;
}

} // namespace stratforge::live::composer
